version: "3.4"
services:
  wms-bod:
    image: swisstopo/mapserver-base:201806061459
    environment:
      - APACHE_PORT=80
      - MS_ERRORFILE=stderr
      - MS_DEBUGLEVEL=0
      - FCGID_IO_TIMEOUT=30
      - FCGID_BUSY_TIMEOUT=30
      - FCGID_BUSY_SCAN_INTERVAL=10
      - FCGID_IO_TIMEOUT=27
      - FCGID_BUSY_TIMEOUT=27
      - FCGID_BUSY_SCAN_INTERVAL=5
      - FCGID_MAX_PROCESSES=200
      - FCGID_MAX_REQUESTS_PER_PROCESS=1000
      - APACHE_LOG_LEVEL=debug
    ports:
      - 8000:80
  db:
    image: kartoza/postgis:12.0
    environment:
      - POSTGRES_DB=bod_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 15432:5432
    volumes:
      - type: bind
        source: ${PWD}/scripts/sql/init_local_db.sql
        target: /docker-entrypoint-initdb.d/setup-db.sql
  s3:
    image: minio/minio
    env_file: ./minio.env
    command: server /data
    volumes:
      - type: bind
        source: ${PWD}/.volumes/minio
        target: /data
    ports:
      - 9090:9000
  rabbitmq:
    image: rabbitmq:3.6-alpine
    environment:
      RABBITMQ_PORT: 5672
    network_mode: "host"
  celery-workers:
    image: "974517877189.dkr.ecr.eu-central-1.amazonaws.com/service-wmts:celery-workers-local"
    build:
      context: .
      target: unittest
    volumes:
      - type: bind
        source: "${PWD}/logs"
        target: /logs
    env_file:
      .env.local
    environment:
      BOD_DB_PORT: 5432
      BOD_DB_HOST: db
      LOGS_DIR: /logs
      LOGGING_CFG: /service-wmts/config/logging-cfg-local.yml
    entrypoint:
      - /scripts/wait-for-it.sh
      - db:5432
      - --
      - celery
      - -A
      - app.celery
      - worker
      - -P
      - gevent
      - --autoscale=17,8
      - --loglevel=info
    depends_on:
      - s3
      - rabbitmq
      - db
