version: "3.4"
services:
  wms-bod:
    image: swisstopo/mapserver-base:201806061459
    environment:
      - APACHE_PORT=80
      - MS_ERRORFILE=stderr
      - MS_DEBUGLEVEL=0
      - FCGID_IO_TIMEOUT=30
      - FCGID_BUSY_TIMEOUT=30
      - FCGID_BUSY_SCAN_INTERVAL=10
      - FCGID_IO_TIMEOUT=27
      - FCGID_BUSY_TIMEOUT=27
      - FCGID_BUSY_SCAN_INTERVAL=5
      - FCGID_MAX_PROCESSES=200
      - FCGID_MAX_REQUESTS_PER_PROCESS=1000
      - APACHE_LOG_LEVEL=debug
  db:
    image: kartoza/postgis:12.0
    environment:
      - POSTGRES_DB=bod_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: bind
        source: ${PWD}/scripts/sql/init_local_db.sql
        target: /docker-entrypoint-initdb.d/setup-db.sql
  rabbitmq:
    image: rabbitmq:3.6-alpine
    environment:
      RABBITMQ_PORT: 5672
  celery-workers:
    image: "974517877189.dkr.ecr.eu-central-1.amazonaws.com/service-wmts:celery-workers-ci"
    build:
      context: .
      target: unittest
    env_file:
      .env.ci
    environment:
      LOGGING_CFG: /service-wmts/config/logging-cfg-ci.yml
    entrypoint:
      - /scripts/wait-for-it.sh
      - db:5432
      - --
      - celery
      - -A
      - app.celery
      - worker
      - -P
      - gevent
      - --autoscale=17,8
      - --loglevel=info
    depends_on:
      - rabbitmq
      - db
  app:
    image: "974517877189.dkr.ecr.eu-central-1.amazonaws.com/service-wmts-ci"
    build:
        context: .
        target: unittest
    entrypoint:
      - /scripts/wait-for-it.sh
      - db:5432
      - --
      - nose2
      - -c tests/unittest.cfg
      - --verbose
      - -s
      - tests/
    env_file:
      .env.ci
    environment:
      LOGGING_CFG: /service-wmts/config/logging-cfg-ci.yml
    depends_on:
      - celery-workers
      - db
