version: "3.4"
services:
  wms-bod:
    image: camptocamp/mapserver:7.6
    environment:
      - MS_DEBUGLEVEL=0
      - LISTEN_PORT_80=1
    volumes:
      - type: bind
        source: ${PWD}/tests/mapserver/mapserver.map
        target: /etc/mapserver/mapserver.map
  db:
    image: kartoza/postgis:12.0
    environment:
      - POSTGRES_DB=bod_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: bind
        source: ${PWD}/scripts/sql/init_local_db.sql
        target: /docker-entrypoint-initdb.d/setup-db.sql
  app:
    image: "974517877189.dkr.ecr.eu-central-1.amazonaws.com/service-wmts-ci"
    build:
        context: .
        target: unittest
    entrypoint:
      - /scripts/wait-for-it.sh
      - db:5432
      - --
      - nose2
      - -c tests/unittest.cfg
      - --verbose
      - -s
      - tests/
    env_file:
      .env.ci
    environment:
      LOGGING_CFG: /service-wmts/config/logging-cfg-ci.yml
    depends_on:
      - db
