version: "3.4"
services:
  s3:
    image: minio/minio
    env_file: ./minio.env
    command: server /data
    volumes:
      - type: bind
        source: ${PWD}/.volumes/minio
        target: /data
    ports:
      - 9090:9000
  rabbitmq:
    image: rabbitmq:3.6-alpine
    environment:
      RABBITMQ_PORT: 5672
    network_mode: "host"
  celery-workers:
    image: "swisstopo/service-wmts:celery-workers-ci"
    build: .
    environment:
      WMTS_PORT: 9000
      WMS_PORT: 8000
      RABBITMQ_PORT: 5672
      LOGGING_CFG: /service-wmts/config/logging-cfg-ci.yml
    entrypoint: []
    command:
      - celery
      - -A
      - app.celery
      - worker
      - -P
      - gevent
      - --autoscale=17,8
      - --loglevel=info
    depends_on:
      - rabbitmq
    network_mode: "host"
  app:
    image: "swisstopo/service-wmts:ci"
    build: .
    ports:
      - "9000:8080"
    entrypoint: nose2 -c tests/unittest.cfg --verbose -s tests/
    environment:
      WMTS_PORT: 9000
      WMS_PORT: 8000
      RABBITMQ_PORT: 5672
      LOGGING_CFG: /service-wmts/config/logging-cfg-ci.yml
    depends_on:
      - celery-workers
